package py.gov.ande.control.gateway.model;
// Generated 07/08/2016 10:31:56 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * ReportingCapability generated by hbm2java
 */
public class ReportingCapability implements java.io.Serializable {

	private int id;
	private String description;
	private Boolean brcb;
	private Boolean urcb;
	private Set<TagMonitorIec61850Operation> tagMonitorIec61850Operations = new HashSet<TagMonitorIec61850Operation>(0);
	private Set<TagMonitorIec61850> tagMonitorIec61850s = new HashSet<TagMonitorIec61850>(0);

	public ReportingCapability() {
	}

	public ReportingCapability(int id, String description) {
		this.id = id;
		this.description = description;
	}

	public ReportingCapability(int id, String description, Boolean brcb, Boolean urcb,
			Set<TagMonitorIec61850Operation> tagMonitorIec61850Operations,
			Set<TagMonitorIec61850> tagMonitorIec61850s) {
		this.id = id;
		this.description = description;
		this.brcb = brcb;
		this.urcb = urcb;
		this.tagMonitorIec61850Operations = tagMonitorIec61850Operations;
		this.tagMonitorIec61850s = tagMonitorIec61850s;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getBrcb() {
		return this.brcb;
	}

	public void setBrcb(Boolean brcb) {
		this.brcb = brcb;
	}

	public Boolean getUrcb() {
		return this.urcb;
	}

	public void setUrcb(Boolean urcb) {
		this.urcb = urcb;
	}

	public Set<TagMonitorIec61850Operation> getTagMonitorIec61850Operations() {
		return this.tagMonitorIec61850Operations;
	}

	public void setTagMonitorIec61850Operations(Set<TagMonitorIec61850Operation> tagMonitorIec61850Operations) {
		this.tagMonitorIec61850Operations = tagMonitorIec61850Operations;
	}

	public Set<TagMonitorIec61850> getTagMonitorIec61850s() {
		return this.tagMonitorIec61850s;
	}

	public void setTagMonitorIec61850s(Set<TagMonitorIec61850> tagMonitorIec61850s) {
		this.tagMonitorIec61850s = tagMonitorIec61850s;
	}

    @Override
    public String toString(){
    	return getDescription();
    }
}
