package py.gov.ande.control.gateway.model;
// Generated 07/08/2016 10:31:56 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * BufferedRcb generated by hbm2java
 */
public class BufferedRcb implements java.io.Serializable {

	private int id;
	private Ied ied;
	private String reference;
	private String dataset;
	private Set<TagMonitorIec61850> tagMonitorIec61850s = new HashSet<TagMonitorIec61850>(0);

	public BufferedRcb() {
	}

	public BufferedRcb(int id, Ied ied, String reference) {
		this.id = id;
		this.ied = ied;
		this.reference = reference;
	}

	public BufferedRcb(int id, Ied ied, String reference, String dataset, Set<TagMonitorIec61850> tagMonitorIec61850s) {
		this.id = id;
		this.ied = ied;
		this.reference = reference;
		this.dataset = dataset;
		this.tagMonitorIec61850s = tagMonitorIec61850s;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Ied getIed() {
		return this.ied;
	}

	public void setIed(Ied ied) {
		this.ied = ied;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public String getDataset() {
		return this.dataset;
	}

	public void setDataset(String dataset) {
		this.dataset = dataset;
	}

	public Set<TagMonitorIec61850> getTagMonitorIec61850s() {
		return this.tagMonitorIec61850s;
	}

	public void setTagMonitorIec61850s(Set<TagMonitorIec61850> tagMonitorIec61850s) {
		this.tagMonitorIec61850s = tagMonitorIec61850s;
	}
	
    @Override
    public String toString(){
    	return getReference();
    }

}
