package py.gov.ande.control.gateway.model;
// Generated 31/07/2016 03:04:36 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * BufferedRcb generated by hbm2java
 */
public class BufferedRcb implements java.io.Serializable {

	private int id;
	private int iedId;
	private String reference;
	private String dataset;

	public BufferedRcb() {
	}

	public BufferedRcb(int id, int iedId, String reference) {
		this.id = id;
		this.iedId = iedId;
		this.reference = reference;
	}

	public BufferedRcb(int id, int iedId, String reference, String dataset) {
		this.id = id;
		this.iedId = iedId;
		this.reference = reference;
		this.dataset = dataset;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getIedId() {
		return this.iedId;
	}

	public void setIedId(int iedId) {
		this.iedId = iedId;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public String getDataset() {
		return this.dataset;
	}

	public void setDataset(String dataset) {
		this.dataset = dataset;
	}

}
