package py.gov.ande.control.gateway.model;
// Generated 07/08/2016 10:31:56 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * BufferedRcbOperation generated by hbm2java
 */
public class BufferedRcbOperation implements java.io.Serializable {

	private int id;
	private IedOperation iedOperation;
	private String reference;
	private String dataset;
	private Set<TagMonitorIec61850Operation> tagMonitorIec61850Operations = new HashSet<TagMonitorIec61850Operation>(0);

	public BufferedRcbOperation() {
	}

	public BufferedRcbOperation(int id, IedOperation iedOperation, String reference) {
		this.id = id;
		this.iedOperation = iedOperation;
		this.reference = reference;
	}

	public BufferedRcbOperation(int id, IedOperation iedOperation, String reference, String dataset,
			Set<TagMonitorIec61850Operation> tagMonitorIec61850Operations) {
		this.id = id;
		this.iedOperation = iedOperation;
		this.reference = reference;
		this.dataset = dataset;
		this.tagMonitorIec61850Operations = tagMonitorIec61850Operations;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public IedOperation getIedOperation() {
		return this.iedOperation;
	}

	public void setIedOperation(IedOperation iedOperation) {
		this.iedOperation = iedOperation;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public String getDataset() {
		return this.dataset;
	}

	public void setDataset(String dataset) {
		this.dataset = dataset;
	}

	public Set<TagMonitorIec61850Operation> getTagMonitorIec61850Operations() {
		return this.tagMonitorIec61850Operations;
	}

	public void setTagMonitorIec61850Operations(Set<TagMonitorIec61850Operation> tagMonitorIec61850Operations) {
		this.tagMonitorIec61850Operations = tagMonitorIec61850Operations;
	}

}
