package py.gov.ande.control.gateway.model;
// Generated 31/07/2016 03:04:36 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * Ied generated by hbm2java
 */
public class Ied implements java.io.Serializable {

	private int id;
	private String name;
	private Integer bufferTime;
	private Integer portAddress;
	private Integer connectionTest;
	private String ipAddress;
	private Date createdAt;
	private Date updateAt;

	public Ied() {
	}

	public Ied(int id) {
		this.id = id;
	}

	public Ied(int id, String name, Integer bufferTime, Integer portAddress, Integer connectionTest, String ipAddress,
			Date createdAt, Date updateAt) {
		this.id = id;
		this.name = name;
		this.bufferTime = bufferTime;
		this.portAddress = portAddress;
		this.connectionTest = connectionTest;
		this.ipAddress = ipAddress;
		this.createdAt = createdAt;
		this.updateAt = updateAt;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getBufferTime() {
		return this.bufferTime;
	}

	public void setBufferTime(Integer bufferTime) {
		this.bufferTime = bufferTime;
	}

	public Integer getPortAddress() {
		return this.portAddress;
	}

	public void setPortAddress(Integer portAddress) {
		this.portAddress = portAddress;
	}

	public Integer getConnectionTest() {
		return this.connectionTest;
	}

	public void setConnectionTest(Integer connectionTest) {
		this.connectionTest = connectionTest;
	}

	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

}
