package py.gov.ande.control.gateway.model;
// Generated 03/07/2016 08:06:53 PM by Hibernate Tools 5.1.0.Alpha1

import java.io.Serializable;

/**
 * Ied generated by hbm2java
 */
public class Ied implements java.io.Serializable {

	private int id;
	private String name;
	private Integer bufferTime;
	private Serializable ipAddress;
	private int portAddress;
	private int connectionTest;

	public Ied() {
	}

	public Ied(int id, String name, Serializable ipAddress, int portAddress, int connectionTest) {
		this.id = id;
		this.name = name;
		this.ipAddress = ipAddress;
		this.portAddress = portAddress;
		this.connectionTest = connectionTest;
	}

	public Ied(int id, String name, Integer bufferTime, Serializable ipAddress, int portAddress, int connectionTest) {
		this.id = id;
		this.name = name;
		this.bufferTime = bufferTime;
		this.ipAddress = ipAddress;
		this.portAddress = portAddress;
		this.connectionTest = connectionTest;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getBufferTime() {
		return this.bufferTime;
	}

	public void setBufferTime(Integer bufferTime) {
		this.bufferTime = bufferTime;
	}

	public Serializable getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(Serializable ipAddress) {
		this.ipAddress = ipAddress;
	}

	public int getPortAddress() {
		return this.portAddress;
	}

	public void setPortAddress(int portAddress) {
		this.portAddress = portAddress;
	}

	public int getConnectionTest() {
		return this.connectionTest;
	}

	public void setConnectionTest(int connectionTest) {
		this.connectionTest = connectionTest;
	}

}
