package py.gov.ande.control.gateway.model;
// Generated 07/08/2016 10:31:56 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * IedOperation generated by hbm2java
 */
public class IedOperation implements java.io.Serializable {

	private int id;
	private String name;
	private Integer bufferTime;
	private Integer portAddress;
	private Integer connectionTest;
	private String ipAddress;
	private Date createdAt;
	private Date updateAt;
	private Set<BufferedRcbOperation> bufferedRcbOperations = new HashSet<BufferedRcbOperation>(0);
	private Set<TagMonitorIec61850Operation> tagMonitorIec61850Operations = new HashSet<TagMonitorIec61850Operation>(0);
	private Set<UnbufferedRcbOperation> unbufferedRcbOperations = new HashSet<UnbufferedRcbOperation>(0);

	public IedOperation() {
	}

	public IedOperation(int id) {
		this.id = id;
	}

	public IedOperation(int id, String name, Integer bufferTime, Integer portAddress, Integer connectionTest,
			String ipAddress, Date createdAt, Date updateAt, Set<BufferedRcbOperation> bufferedRcbOperations,
			Set<TagMonitorIec61850Operation> tagMonitorIec61850Operations,
			Set<UnbufferedRcbOperation> unbufferedRcbOperations) {
		this.id = id;
		this.name = name;
		this.bufferTime = bufferTime;
		this.portAddress = portAddress;
		this.connectionTest = connectionTest;
		this.ipAddress = ipAddress;
		this.createdAt = createdAt;
		this.updateAt = updateAt;
		this.bufferedRcbOperations = bufferedRcbOperations;
		this.tagMonitorIec61850Operations = tagMonitorIec61850Operations;
		this.unbufferedRcbOperations = unbufferedRcbOperations;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getBufferTime() {
		return this.bufferTime;
	}

	public void setBufferTime(Integer bufferTime) {
		this.bufferTime = bufferTime;
	}

	public Integer getPortAddress() {
		return this.portAddress;
	}

	public void setPortAddress(Integer portAddress) {
		this.portAddress = portAddress;
	}

	public Integer getConnectionTest() {
		return this.connectionTest;
	}

	public void setConnectionTest(Integer connectionTest) {
		this.connectionTest = connectionTest;
	}

	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdateAt() {
		return this.updateAt;
	}

	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	public Set<BufferedRcbOperation> getBufferedRcbOperations() {
		return this.bufferedRcbOperations;
	}

	public void setBufferedRcbOperations(Set<BufferedRcbOperation> bufferedRcbOperations) {
		this.bufferedRcbOperations = bufferedRcbOperations;
	}

	public Set<TagMonitorIec61850Operation> getTagMonitorIec61850Operations() {
		return this.tagMonitorIec61850Operations;
	}

	public void setTagMonitorIec61850Operations(Set<TagMonitorIec61850Operation> tagMonitorIec61850Operations) {
		this.tagMonitorIec61850Operations = tagMonitorIec61850Operations;
	}

	public Set<UnbufferedRcbOperation> getUnbufferedRcbOperations() {
		return this.unbufferedRcbOperations;
	}

	public void setUnbufferedRcbOperations(Set<UnbufferedRcbOperation> unbufferedRcbOperations) {
		this.unbufferedRcbOperations = unbufferedRcbOperations;
	}

}
