package py.gov.ande.control.gateway.model;
// Generated 04/08/2016 11:11:02 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * InformationType generated by hbm2java
 */
public class InformationType implements java.io.Serializable {

	private int id;
	private String description;
	private Set<TagMonitorIec61850> tagMonitorIec61850s = new HashSet<TagMonitorIec61850>(0);

	public InformationType() {
	}

	public InformationType(int id, String description) {
		this.id = id;
		this.description = description;
	}

	public InformationType(int id, String description, Set<TagMonitorIec61850> tagMonitorIec61850s) {
		this.id = id;
		this.description = description;
		this.tagMonitorIec61850s = tagMonitorIec61850s;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<TagMonitorIec61850> getTagMonitorIec61850s() {
		return this.tagMonitorIec61850s;
	}

	public void setTagMonitorIec61850s(Set<TagMonitorIec61850> tagMonitorIec61850s) {
		this.tagMonitorIec61850s = tagMonitorIec61850s;
	}
	
    @Override
    public String toString(){
    	return getDescription();
    }

}
