package py.gov.ande.control.gateway.model;
// Generated 18/07/2016 01:42:16 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * Normalization generated by hbm2java
 */
public class Normalization implements java.io.Serializable {

	private int id;
	private String description;
	private Boolean binary;

	public Normalization() {
	}

	public Normalization(int id, String description) {
		this.id = id;
		this.description = description;
	}

	public Normalization(int id, String description, Boolean binary) {
		this.id = id;
		this.description = description;
		this.binary = binary;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getBinary() {
		return this.binary;
	}

	public void setBinary(Boolean binary) {
		this.binary = binary;
	}

}
