package py.gov.ande.control.gateway.model;
// Generated 05/07/2016 01:12:05 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * ReportingCapacibility generated by hbm2java
 */
public class ReportingCapacibility implements java.io.Serializable {

	private int id;
	private String description;
	private Boolean brcb;
	private Boolean urcb;

	public ReportingCapacibility() {
	}

	public ReportingCapacibility(int id, String description) {
		this.id = id;
		this.description = description;
	}

	public ReportingCapacibility(int id, String description, Boolean brcb, Boolean urcb) {
		this.id = id;
		this.description = description;
		this.brcb = brcb;
		this.urcb = urcb;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getBrcb() {
		return this.brcb;
	}

	public void setBrcb(Boolean brcb) {
		this.brcb = brcb;
	}

	public Boolean getUrcb() {
		return this.urcb;
	}

	public void setUrcb(Boolean urcb) {
		this.urcb = urcb;
	}

}
