package py.gov.ande.control.gateway.model;
// Generated 04/08/2016 11:11:02 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * TagCommandIec61850 generated by hbm2java
 */
public class TagCommandIec61850 implements java.io.Serializable {

	private int id;
	private Boolean use;
	private String name;
	private Integer typeId;
	private String telegramAddress;
	private Integer normalizationId;
	private int iedId;

	public TagCommandIec61850() {
	}

	public TagCommandIec61850(int id, String name, int iedId) {
		this.id = id;
		this.name = name;
		this.iedId = iedId;
	}

	public TagCommandIec61850(int id, Boolean use, String name, Integer typeId, String telegramAddress,
			Integer normalizationId, int iedId) {
		this.id = id;
		this.use = use;
		this.name = name;
		this.typeId = typeId;
		this.telegramAddress = telegramAddress;
		this.normalizationId = normalizationId;
		this.iedId = iedId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Boolean getUse() {
		return this.use;
	}

	public void setUse(Boolean use) {
		this.use = use;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	public String getTelegramAddress() {
		return this.telegramAddress;
	}

	public void setTelegramAddress(String telegramAddress) {
		this.telegramAddress = telegramAddress;
	}

	public Integer getNormalizationId() {
		return this.normalizationId;
	}

	public void setNormalizationId(Integer normalizationId) {
		this.normalizationId = normalizationId;
	}

	public int getIedId() {
		return this.iedId;
	}

	public void setIedId(int iedId) {
		this.iedId = iedId;
	}

}
