package py.gov.ande.control.gateway.model;
// Generated 04/08/2016 11:11:02 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * TagMonitorIec61850 generated by hbm2java
 */
public class TagMonitorIec61850 implements java.io.Serializable {

	private int id;
	private BufferedRcb bufferedRcb;
	private Ied ied;
	private InformationType informationType;
	private Normalization normalization;
	private ReportingCapability reportingCapability;
	private UnbufferedRcb unbufferedRcb;
	private Boolean use;
	private String name;
	private String telegramAddress;
	private Boolean buffered;
	private Boolean unbuffered;

	public TagMonitorIec61850() {
	}

	public TagMonitorIec61850(int id, Ied ied, String telegramAddress) {
		this.id = id;
		this.ied = ied;
		this.telegramAddress = telegramAddress;
	}

	public TagMonitorIec61850(int id, BufferedRcb bufferedRcb, Ied ied, InformationType informationType,
			Normalization normalization, ReportingCapability reportingCapability, UnbufferedRcb unbufferedRcb,
			Boolean use, String name, String telegramAddress, Boolean buffered, Boolean unbuffered) {
		this.id = id;
		this.bufferedRcb = bufferedRcb;
		this.ied = ied;
		this.informationType = informationType;
		this.normalization = normalization;
		this.reportingCapability = reportingCapability;
		this.unbufferedRcb = unbufferedRcb;
		this.use = use;
		this.name = name;
		this.telegramAddress = telegramAddress;
		this.buffered = buffered;
		this.unbuffered = unbuffered;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public BufferedRcb getBufferedRcb() {
		return this.bufferedRcb;
	}

	public void setBufferedRcb(BufferedRcb bufferedRcb) {
		this.bufferedRcb = bufferedRcb;
	}

	public Ied getIed() {
		return this.ied;
	}

	public void setIed(Ied ied) {
		this.ied = ied;
	}

	public InformationType getInformationType() {
		return this.informationType;
	}

	public void setInformationType(InformationType informationType) {
		this.informationType = informationType;
	}

	public Normalization getNormalization() {
		return this.normalization;
	}

	public void setNormalization(Normalization normalization) {
		this.normalization = normalization;
	}

	public ReportingCapability getReportingCapability() {
		return this.reportingCapability;
	}

	public void setReportingCapability(ReportingCapability reportingCapability) {
		this.reportingCapability = reportingCapability;
	}

	public UnbufferedRcb getUnbufferedRcb() {
		return this.unbufferedRcb;
	}

	public void setUnbufferedRcb(UnbufferedRcb unbufferedRcb) {
		this.unbufferedRcb = unbufferedRcb;
	}

	public Boolean getUse() {
		return this.use;
	}

	public void setUse(Boolean use) {
		this.use = use;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTelegramAddress() {
		return this.telegramAddress;
	}

	public void setTelegramAddress(String telegramAddress) {
		this.telegramAddress = telegramAddress;
	}

	public Boolean getBuffered() {
		return this.buffered;
	}

	public void setBuffered(Boolean buffered) {
		this.buffered = buffered;
	}

	public Boolean getUnbuffered() {
		return this.unbuffered;
	}

	public void setUnbuffered(Boolean unbuffered) {
		this.unbuffered = unbuffered;
	}

}
