package py.gov.ande.control.gateway.model;
// Generated 07/08/2016 10:31:56 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * UnbufferedRcb generated by hbm2java
 */
public class UnbufferedRcb implements java.io.Serializable {

	private int id;
	private Ied ied;
	private String referent;
	private String dataset;
	private Set<TagMonitorIec61850> tagMonitorIec61850s = new HashSet<TagMonitorIec61850>(0);

	public UnbufferedRcb() {
	}

	public UnbufferedRcb(int id, Ied ied, String referent) {
		this.id = id;
		this.ied = ied;
		this.referent = referent;
	}

	public UnbufferedRcb(int id, Ied ied, String referent, String dataset,
			Set<TagMonitorIec61850> tagMonitorIec61850s) {
		this.id = id;
		this.ied = ied;
		this.referent = referent;
		this.dataset = dataset;
		this.tagMonitorIec61850s = tagMonitorIec61850s;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Ied getIed() {
		return this.ied;
	}

	public void setIed(Ied ied) {
		this.ied = ied;
	}

	public String getReferent() {
		return this.referent;
	}

	public void setReferent(String referent) {
		this.referent = referent;
	}

	public String getDataset() {
		return this.dataset;
	}

	public void setDataset(String dataset) {
		this.dataset = dataset;
	}

	public Set<TagMonitorIec61850> getTagMonitorIec61850s() {
		return this.tagMonitorIec61850s;
	}

	public void setTagMonitorIec61850s(Set<TagMonitorIec61850> tagMonitorIec61850s) {
		this.tagMonitorIec61850s = tagMonitorIec61850s;
	}

    @Override
    public String toString(){
    	return getReferent();
    }
}
