package py.gov.ande.control.gateway.model;
// Generated 21/07/2016 02:30:07 PM by Hibernate Tools 5.1.0.Alpha1

/**
 * UnbufferedRcb generated by hbm2java
 */
public class UnbufferedRcb implements java.io.Serializable {

	private int id;
	private int iedId;
	private String referent;
	private String dataset;

	public UnbufferedRcb() {
	}

	public UnbufferedRcb(int id, int iedId, String referent) {
		this.id = id;
		this.iedId = iedId;
		this.referent = referent;
	}

	public UnbufferedRcb(int id, int iedId, String referent, String dataset) {
		this.id = id;
		this.iedId = iedId;
		this.referent = referent;
		this.dataset = dataset;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getIedId() {
		return this.iedId;
	}

	public void setIedId(int iedId) {
		this.iedId = iedId;
	}

	public String getReferent() {
		return this.referent;
	}

	public void setReferent(String referent) {
		this.referent = referent;
	}

	public String getDataset() {
		return this.dataset;
	}

	public void setDataset(String dataset) {
		this.dataset = dataset;
	}

}
